acts.settings:
  type: bootstrap5.settings
  label: 'ACTS theme settings'
  mapping:
    features:
      type: mapping
      label: 'Theme features'
      mapping:
        node_user_picture:
          type: boolean
          label: 'Display author picture on nodes'
        comment_user_picture:
          type: boolean
          label: 'Display user pictures in comments'
        comment_user_verification:
          type: boolean
          label: 'Enable comment user verification'
        favicon:
          type: boolean
          label: 'Use favicon'

    logo:
      type: mapping
      label: 'Logo settings'
      mapping:
        use_default:
          type: boolean
          label: 'Use the default logo'
        path:
          type: string
          label: 'Custom logo path'

    favicon:
      type: mapping
      label: 'Favicon settings'
      mapping:
        use_default:
          type: boolean
          label: 'Use the default favicon'

    subtheme_folder:
      type: string
      label: 'Subtheme folder path'
    subtheme_name:
      type: string
      label: 'Subtheme name'
    subtheme_machine_name:
      type: string
      label: 'Subtheme machine name'
