<?php

/**
 * @file
 * Contains hook implementations for the ACTS Core module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_presave.
 */
function acts_core_node_presave(EntityInterface $node) {
  if ($node->bundle() == 'person') {
    $title[] = $node->get('field_title')->value;
    $title[] = $node->get('field_first_name')->value;
    $title[] = $node->get('field_last_name')->value;
    if ($comment = $node->get('field_disambiguation_comment')->value) {
      $title[] = "(${comment})";
    }
    $node->setTitle(trim(implode(' ', $title)));
  }
}
