<?php

/**
 * @file
 * Contains hook implementations for the ACTS Core module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_presave.
 */
function acts_core_node_presave(EntityInterface $node) {
  if ($node->bundle() == 'person') {
    $first_name = $node->get('field_first_name')->value;
    $last_name = $node->get('field_last_name')->value;
    $node->setTitle($first_name . ' ' . $last_name);
  }
}
